export const SYLLABUS: Record<string, Record<string, string[]>> = {
  '6': {
    Math: [
      'Patterns in Mathematics',
      'Lines and Angles',
      'Number Play',
      'Data Handling and Presentation',
      'Prime Time',
      'Perimeter and Area',
      'Fractions',
      'Playing with Constructions',
      'Symmetry',
      'The Other Side of Zero',
    ],
    Science: [
      'The Wonderful World of Science',
      'Diversity in the Living World',
      'Mindful Eating: A Path to a Healthy Body',
      'Separation of Substances in Everyday Life',
      'Materials Around Us',
      'Curiosity: A Wonder Called Universe',
      'A Peek into Electricity',
      'Our Skeletal System and Skin',
      'Methods of Separation in Everyday Life',
      'Living Creatures: Exploring Their Characteristics',
      "Nature's Treasures",
      'Beyond Earth',
    ],
  },
  '7': {
    Math: [
      'Large Numbers Around Us',
      'Arithmetic Expressions',
      'Fractions and Decimals',
      'Lines and Angles',
      'Ratio and Proportion',
      'Constructions and Tilings',
      'Finding the Unknown (Algebra)',
      'Connecting the Dots',
    ],
    Science: [
      'Nutrition in Plants',
      'Nutrition in Animals',
      'Heat Transfer and Its Effects',
      'Acids, Bases and Salts',
      'Physical and Chemical Changes',
      'Weather, Climate and Adaptation',
      'Winds, Storms and Cyclones',
      'Light',
      'Electric Current and its Effects',
      'Water: A Precious Resource',
      'Forests: Our Lifeline',
      'Wastewater Management',
    ],
  },
  '8': {
    Math: [
      'A Square and A Cube',
      'Power Play',
      'A Story of Numbers',
      'Quadrilaterals',
      'Number Play',
      'We Distribute Yet Things Multiply',
      'Proportional Reasoning',
      'Fractions in Disguise',
      'The Baudhayana–Pythagoras Theorem',
      'Proportional Reasoning – 2',
      'Exploring Some Geometric Themes',
      'Tales by Dots and Lines',
      'Algebra Play',
      'Area',
    ],
    Science: [
      'Crop Production and Management',
      'The Invisible Living World (Microorganisms)',
      'Health and Diseases',
      'From Clothes to Fibres',
      'Combustion and Flame',
      'Force and Pressure',
      'Friction',
      'Sound',
      'Electricity and its Effects',
      'Light',
      'Some Natural Phenomena',
      'How Nature Works in Harmony (Ecosystems)',
      'Our Home: Earth, a Unique Life Sustaining Planet',
    ],
  },
  '9': {
    Math: [
      'Number Systems',
      'Polynomials',
      'Coordinate Geometry',
      'Linear Equations in Two Variables',
      'Introduction to Euclid\'s Geometry',
      'Lines and Angles',
      'Triangles',
      'Quadrilaterals',
      'Circles',
      'Heron\'s Formula',
      'Surface Areas and Volumes',
      'Statistics',
    ],
    Science: [
      'Matter in Our Surroundings',
      'Is Matter Around Us Pure?',
      'Atoms and Molecules',
      'Structure of the Atom',
      'The Fundamental Unit of Life (Cell)',
      'Tissues',
      'Motion',
      'Force and Laws of Motion',
      'Gravitation',
      'Work and Energy',
      'Sound',
      'Improvement in Food Resources',
    ],
  },
  '10': {
    Math: [
      'Real Numbers',
      'Polynomials',
      'Pair of Linear Equations in Two Variables',
      'Quadratic Equations',
      'Arithmetic Progressions',
      'Triangles',
      'Coordinate Geometry',
      'Introduction to Trigonometry',
      'Some Applications of Trigonometry',
      'Circles',
      'Areas Related to Circles',
      'Surface Areas and Volumes',
      'Statistics',
      'Probability',
    ],
    Science: [
      'Chemical Reactions and Equations',
      'Acids, Bases and Salts',
      'Metals and Non-metals',
      'Carbon and its Compounds',
      'Life Processes',
      'Control and Coordination',
      'How Do Organisms Reproduce?',
      'Heredity',
      'Light — Reflection and Refraction',
      'Human Eye and the Colourful World',
      'Electricity',
      'Magnetic Effects of Electric Current',
      'Our Environment',
    ],
  },
};
